### ISSUE TITLE
npm install failure : missing dependency "blockui"

### ISSUE THREAD

**Issue by andrewspiers** [agaveplatform/microsites#1]
I just had npm install fail on a new clone with the following error:

`
bower blockUI#*                                   ECMDERR Failed to execute "git ls-remote --tags --heads https://github.com/ueqt/blockui.git", exit code of #128 remote: Repository not found. fatal: Authentication failed for 'https://github.com/ueqt/blockui.git/'

Additional error details:
remote: Repository not found.
fatal: Authentication failed for 'https://github.com/ueqt/blockui.git/'
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! togo-micro-app@1.0.0 postinstall: `node_modules/bower/bin/bower install && node_modules/gulp/bin/gulp.js sass minify`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the togo-micro-app@1.0.0 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /OSM/HOME-MEL/spi072/.npm/_logs/2018-06-15T02_01_53_729Z-debug.log
`

And it does indeed appear that github.com/ueqt/blockui does not exist.

**Comment by deardooley** [comment]
This should be fixed. I still need to update the build to flatten the gh_pages branch for proper hosting on here, but aside from that, you should be good to go. Dockerfile and build have been updated as well. Check the README for full details.
